use serde::{Deserialize, Serialize};
use std::fmt;
use time::{Date, Duration, OffsetDateTime, macros::format_description};

#[derive(Serialize, Deserialize, Debug)]
pub struct Habit {
    name: String,
    timestamps: Vec<OffsetDateTime>,
}

impl Habit {
    pub fn new(name: String) -> Habit {
        Habit {
            name,
            timestamps: Vec::new(),
        }
    }

    pub fn mark_complete(&mut self, datetime: OffsetDateTime) {
        self.timestamps.push(datetime);
    }

    pub fn done_on_date(&self, date: Date) -> bool {
        self.timestamps
            .iter()
            .any(|datetime| datetime.date() == date)
    }

    pub fn change_name(&mut self, new_name: String) {
        self.name = new_name
    }

    pub fn reset_completions(&mut self) {
        self.timestamps = Vec::new();
    }

    pub fn list_times(&self, date: Date) -> String {
        let format = format_description!("[hour]:[minute]");
        self.timestamps
            .iter()
            .filter(|&odt| odt.date() == date)
            .map(|d| d.format(&format).unwrap_or("unknown".to_string()))
            .collect::<Vec<_>>()
            .join(", ")
    }

    // written by ChatGPT
    pub fn ending_streak(&self, today: Date) -> usize {
        if self.timestamps.is_empty() {
            return 0;
        }

        // 1. Prepare the data.
        let mut dates: Vec<Date> = self.timestamps.iter().map(|dt| dt.date()).collect();
        dates.sort();
        dates.dedup();

        // 2. Identify our anchor points.
        let yesterday = today - Duration::DAY;

        // 3. Determine the starting point of the walk.
        // The streak is active if the most recent entry is Today OR Yesterday.
        let mut current_check = if dates.contains(&today) {
            today
        } else if dates.contains(&yesterday) {
            yesterday
        } else {
            // If the last entry was 2+ days ago, the streak is broken.
            return 0;
        };

        // 4. Walk backward through the calendar.
        let mut count = 0;
        while dates.contains(&current_check) {
            count += 1;
            current_check -= Duration::DAY;
        }

        count
    }

    // number of days with a completion in a 30-day window ending today
    pub fn last_30_days(&self, today: Date) -> usize {
        let mut dates: Vec<Date> = self.timestamps.iter().map(|dt| dt.date()).collect();
        dates.sort();
        dates.dedup();

        let month_ago: Date = today - Duration::DAY * 30;
        dates.iter().filter(|&&dt| dt > month_ago).count()
    }
}

impl fmt::Display for Habit {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.pad(&self.name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use time::macros::{date, datetime};

    // generated by ChatGPT
    #[test]
    fn last_30_days_handles_edge_cases() {
        let today = date!(2026 - 03 - 26);

        let habit = Habit {
            name: "test".to_string(),
            timestamps: vec![
                // today: should count
                datetime!(2026-03-26 08:00:00 +00:00),
                datetime!(2026-03-26 21:30:00 +00:00), // same day, should NOT add another count
                // 1 day ago: should count
                datetime!(2026-03-25 12:00:00 +00:00),
                // 29 days ago: should count
                datetime!(2026-02-25 09:00:00 +00:00),
                datetime!(2026-02-25 18:00:00 +00:00), // same day, should NOT add another count
                // exactly 30 days ago: should NOT count with current logic (dt > month_ago)
                datetime!(2026-02-24 10:00:00 +00:00),
                // 31 days ago: should NOT count
                datetime!(2026-02-23 10:00:00 +00:00),
            ],
        };

        assert_eq!(habit.last_30_days(today), 3);
    }

    // generated by ChatGPT
    #[test]
    fn last_30_days_is_zero_when_no_timestamps() {
        let today = date!(2026 - 03 - 26);
        let habit = Habit::new("test".to_string());
        assert_eq!(habit.last_30_days(today), 0);
    }
}
